user:
  max_length_name: 50
  max_length_email: 255
  min_length_password: 6
  remember_me: "1"
  gravatar_home: 50
  password_reset_expire: 2
  gravatar:
    size: 50
users:
  per_page: 10
microposts:
  per_page: 5
micropost:
  content:
    max_length: 140
  picture:
    max_mb: 5
  accept: "image/jpeg,image/gif,image/png"
carrier_ware:
  picture_upload:
    start: 400
    end: 400
gravatar:
  size: 50
  follow: 30
follows:
  per_page: 10
